### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by MicheleBertoli** [MicheleBertoli/franz-spectrum#1]
The [documentation](https://github.com/meetfranz/plugins/blob/master/docs/integration.md#icons) says:
> In order to show every service icon crystal clear within the Franz UI, we require a .svg and .png in 1024x1024px.

cc @mxstbr

**Comment by mxstbr** [comment]
Would you rather want rounded corners

![homescreen-icon-512x512](https://user-images.githubusercontent.com/7525670/32147678-675e7bb4-bceb-11e7-8896-cc6078f44047.png)

Or full square

![apple-icon-144x144-precomposed](https://user-images.githubusercontent.com/7525670/32147679-725a4c96-bceb-11e7-9cf2-5f2c2e1bea78.png)

?

**Comment by MicheleBertoli** [comment]
I'd say rounded, as other apps within Franz have rounded borders as well.
Thank you very much!

**Comment by superbryntendo** [comment]
@mxstbr, idk where you want these, so... here's your icons: http://c.bryn.io/nNdZ

For future reference, the square one is our "avatar" and should only be used inside a frame, otherwise if it's free-standing, use the squircle as that's our "icon"
