### ISSUE TITLE
Noice

### ISSUE THREAD

**Issue by mxstbr** [MicheleBertoli/franz-spectrum#2]
/cc @adlk

**Comment by MicheleBertoli** [comment]
I'm glad you like this, @mxstbr :)
I'll be more than happy to add you as admin and/or transfer the repo.
What I really want is being able to use Spectrum within Franz.
Thank you very much!

**Comment by mxstbr** [comment]
I guess we could take this over and maintain it, what's missing?

**Comment by MicheleBertoli** [comment]
That'd be awesome.
Once you pushed the icons, I think it's ready to be [deployed](https://github.com/meetfranz/plugins/blob/master/docs/integration.md#user-content-deployment).
I tried the notifications count locally and it works.
Thank you very much!

**Comment by MicheleBertoli** [comment]
I transferred the repo to you:
> This repository is being transferred to @mxstbr.
And added your name as `author`, and in the licence.
Please let me know if everything is OK.
Thank you very much!

**Comment by MicheleBertoli** [comment]
I transferred the repo to you:
> This repository is being transferred to @mxstbr.

And added your name as `author`, and in the licence.
Please let me know if everything is OK.
Thank you very much!

**Comment by mxstbr** [comment]
Oh thanks, I'll clean it up soon.

**Comment by MicheleBertoli** [comment]
As you might have noticed by my activity on Spectrum, I'm currently using this with Franz (in dev mode).
Please feel free to take over the repo and deploy the recipe.
Thank you very much!

**Comment by mxstbr** [comment]
Can you invite me again? :angel: I forgot to accept and the moving invitation has expired. If you can, it'd be great to move it to @withspectrum, but I dunno if GitHub let's you do that. Otherwise let's just move it to me and I'll move it to @withspectrum.

**Comment by MicheleBertoli** [comment]
GitHub says:

> You don’t have the permission to create repositories on withspectrum

So, I transferred it to you:

> This repository is being transferred to @mxstbr.

Thank you very much one more time.
I really want to use Spectrum more, and I hope other users will benefit from this Franz recipe as well.

**Comment by mxstbr** [comment]
Awesome! Thank you for hacking this together :ok:

**Comment by adlk** [comment]
Deployed, thanks for making this!
<img width="936" alt="bildschirmfoto 2017-10-31 um 19 22 31" src="https://user-images.githubusercontent.com/3265004/32241601-e67b86ea-be70-11e7-88d0-00620fef0236.png">

**Comment by MicheleBertoli** [comment]
🙌
